### ISSUE TITLE
Summarize plug-in does not work in backed mode

### ISSUE THREAD

**Issue by jfoster17** [gluesolutions/glue-single-cell#39]
After save/restore

```Traceback (most recent call last):
  File "/Users/jfoster/Desktop/glue-join-on-key-ui-2/glue/glue/utils/misc.py", line 55, in result
    return func(*args, **kwargs)
  File "/Users/jfoster/Desktop/JAX/glue-single-cell/glue-single-cell/glue_single_cell/menubar_plugin.py", line 16, in pca_subset_exp_plugin
    PCASubsetDialog.summarize(data_collection,
  File "/Users/jfoster/Desktop/JAX/glue-single-cell/glue-single-cell/glue_single_cell/qt/pca_subset.py", line 270, in summarize
    self._apply()
  File "/Users/jfoster/Desktop/JAX/glue-single-cell/glue-single-cell/glue_single_cell/qt/pca_subset.py", line 247, in _apply
    data_arr = do_calculation_over_gene_subset(data_with_Xarray, genesubset, calculation = key)
  File "/Users/jfoster/Desktop/JAX/glue-single-cell/glue-single-cell/glue_single_cell/qt/pca_subset.py", line 45, in do_calculation_over_gene_subset
    adata = data_with_Xarray.Xdata
  File "/Users/jfoster/Desktop/JAX/glue-single-cell/glue-single-cell/glue_single_cell/data.py", line 113, in Xdata
    return self.get_object(cls=anndata.AnnData)
  File "/Users/jfoster/Desktop/glue-join-on-key-ui-2/glue/glue/core/data.py", line 297, in get_object
    return handler.to_object(self, **kwargs)
  File "/Users/jfoster/Desktop/JAX/glue-single-cell/glue-single-cell/glue_single_cell/data.py", line 524, in to_object
    adata = anndata.AnnData(data_or_subset['Xarray'], obs=obs_data, var=var_data)
  File "/Users/jfoster/opt/anaconda3/envs/single-cell/lib/python3.9/site-packages/anndata/_core/anndata.py", line 291, in __init__
    self._init_as_actual(
  File "/Users/jfoster/opt/anaconda3/envs/single-cell/lib/python3.9/site-packages/anndata/_core/anndata.py", line 448, in _init_as_actual
    raise ValueError(
ValueError: `X` needs to be of one of ndarray, MaskedArray, spmatrix, ZarrArray, ZappyArray, Array, not <class 'h5py._hl.dataset.Dataset'>.
```

Probably a difference between how the file is loaded on restore versus on first creation...

**Comment by jfoster17** [comment]
This was a problem with how we were restoring DataAnnData objects in backed mode.
